### ISSUE TITLE
Tracking Issue: Implementing a column-based memtable

### ISSUE THREAD

**Issue by tanruixiang** [apache/horaedb#1093]
### Describe This Problem

Implementing a column-based memtable

We'll be developing in the `impl-column-based-memtable` branch, which will eventually merge into the main branch using cherry-pick.
### Proposal

Implementing a column-based memtable

### Additional Context

- [ ] Designing a columnar memtable approach(There's already a first draft) @tanruixiang 
- [ ] https://github.com/CeresDB/ceresdb/issues/1094 @chunshao90 
- [ ] https://github.com/CeresDB/ceresdb/issues/1095 @tanruixiang 
- [ ] https://github.com/CeresDB/ceresdb/issues/1096 @chunshao90 @tanruixiang 
- [ ] Optimize performance in high concurrency read/write scenarios @tanruixiang
