### ISSUE TITLE
Tracking issue for compaction offloading

### ISSUE THREAD

**Issue by LeslieKid** [apache/horaedb#1545]
### Describe This Problem

We found in production that the speed of sst compaction is unable to keep up with the speed of sst generation, leading to poor query performance. However we are unable give more resource to compaction to solve the problem because query/write is more important than compaction in the same node.

It is really hard to do a trade-off about resource allocation among query, write and compaction in lsm model. We want to compact the generated small ssts as fast as possible, but we can't tolerate its influence to query/write. And finally I think offload the compaction to the seperated nodes may be the key for it.

### Proposal

**The following is the architecture for compaction offloading.**

![Architecture.png](https://s2.loli.net/2024/07/17/ivH4E2MJq8pZbnQ.png)

To support compaction offloading, we need:

- **Compaction server supporting remote compaction service (Execute Plane)**
  - [ ] Introduce runnable compaction server and expose the api  for horaedb node to ask for remote compaction service
- **Horaemeta supports managing the compaction servers (Control Plane)**
  - [ ] Impl the ability to manage the compaction servers and collect their status (Monitor)
  - [ ] Impl scheduling algorithm for load balance and expose the api for horaedb node to get the proper remote compaction node (Scheduler)
- **Horaedb node supports submitting the compaction task to remote**
  - [ ] Impl remote mode compactor based on the provided compaction service and horaemeta service above

### Additional Context

This issue replaces issue #1480. Please close issue #1480 as it is outdated.

[incubator-horaedb-proto#133](https://github.com/apache/incubator-horaedb-proto/issues/133) is highly related to this issue.

**Comment by Rachelint** [comment]
looks great!

**Comment by LeslieKid** [comment]
> I think in the first stage, we can treat the `compaction cluster` as same as the `horaedb cluster`. And we just reuse the ability about monitoring and scheduling for `horaedb cluster` in `horaemeta`.
> 
> And we can start to desigin the specific `schedule` strategy for `compaction cluster` after it can work.

Thanks for your suggestion! I think it's a good idea to first implement a simple working version.

**Comment by Rachelint** [comment]
I think `Horaedb node supports submitting the compaction task to remote` may be similar as `Compaction node supporting remote compaction service `.

I guess the third step can be integration test, test is very important actually.

**Comment by Rachelint** [comment]
Maybe you will be insterested when writing test
https://github.com/apache/horaedb/tree/main/integration_tests/dist_query
